### ISSUE TITLE
Error when running in project

### ISSUE THREAD

**Issue by allforabit** [brunchboy/afterglow#7]
I'm getting the following error when running the code in the readme:

`CompilerException java.lang.NoClassDefFoundError: Could not initialize class afterglow.core__init`

```
(defproject example "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [afterglow "0.1.4"]]
  :main ^:skip-aot example.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

I am however able to run the examples if I clone the afterglow repo and then run.

I don't get this error when using other libraries such as overtone.midi. I'm quite new to clojure so I may be missing something obvious. I'm working on OS X Yosemite.

Thanks, looks like a great project and would love to get experimenting with it!

**Comment by brunchboy** [comment]
Hello! I’m trying to reproduce what you reported above, although I am not certain about the exact sequence of steps you followed which led to that exception, and without a more complete stack trace, it’s a bit hard for me to speculate about exactly what might have gone wrong.

Here’s what I’ve tried:

    lein new example

to create a new basic Clojure project framework, like you seem to have. And then I used `cd` into the new `example` directory and replaced the `project.clj` file with what you pasted above. When I did that, and typed `lein repl`, I got a repl in the namespace `example.core` which makes sense given the project spec. But what exactly did you do next? Here’s what I did, based on the example I thought you were following:

```clojure
(require 'afterglow.examples)
;; -> nil
```

That seemed to work ok...

```clojure
(in-ns 'afterglow.examples)
;;-> #object[clojure.lang.Namespace 0x1983f125 "afterglow.examples"]
```

Still seeming on track...

```clojure
(core/start-web-server 16000 true)
;;-> true
```

And the web UI pops up like I expect, so everything seems fine for me. What was different in your approach? (As it happens, I am on OS X Yosemite as well.)

It would probably be faster to discuss this on the [Gitter chat](https://gitter.im/brunchboy/afterglow) if that works for you too.

**Comment by allforabit** [comment]
Thanks James for getting back to me so quickly. I tried following these steps and got an error when I entered `(require 'afterglow.examples)`. It was a different error this time however. When I retried it I got the same error as I got previously. Maybe it's the version of java I'm using. This caused issues for me before. Below is a readout of my repl:

```
nREPL server started on port 63895 on host 127.0.0.1 - nrepl://127.0.0.1:63895
REPL-y 0.3.7, nREPL 0.2.10
Clojure 1.7.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-b25
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

example.core=> (require 'afterglow.examples)

CompilerException java.lang.ExceptionInInitializerError, compiling:(afterglow/examples.clj:1:1) 
example.core=> (require 'afterglow.examples)

CompilerException java.lang.NoClassDefFoundError: Could not initialize class afterglow.core__init, compiling:(afterglow/examples.clj:1:1) 
```

Unfortunately the error messages aren't very descriptive. 

Yes we can use Gitter if you that's easier. I haven't used it before, but have signed up now so you can get back to me on that if you like.

Thanks again!

Kevin

**Comment by brunchboy** [comment]
Wow, that’s incredibly frustrating. There is no stack trace showing up at all? I can’t imagine how we are supposed to debug the problem. I notice that you are using a different version of nREPL than I am (I’m on 0.2.11 for compatibility with CIDER), but I tried dropping back to 0.2.10 and that did not break things the way they are for you. What version of Leiningen are you using?

    lein --version
    Leiningen 2.5.3 on Java 1.8.0_51 Java HotSpot(TM) 64-Bit Server VM

I would be surprised if the Java version is the problem, we are pretty close in that regard. I am going to post a question on the Clojure mailing list to see if anyone has seen anything like this, or has any suggestions about how we can try to load smaller pieces and see stack traces with root causes when things fail.

As far as Gitter goes, that can be faster if we are both at our workstations at the same time, but since we are still in flailing-madly research mode at this point, we can stay here too.

**Comment by ryfow** [comment]
`lein deps :tree` may reveal a dependency conflict.

**Comment by allforabit** [comment]
Here's the output from lein -v:
Leiningen 2.5.3 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM

I ran the `lein deps :tree` and it suggested some inclusions which I implemented. It didn't solve the problem however. `[afterglow "0.1.4" :exclusions [org.clojure/tools.nrepl cider/cider-nrepl clj-time]]`

The odd thing is it works perfectly from the cloned repo. No errors at all. 

Here's the last bit of output from the `require 'afterglow.examples :verbose)`:

```
(clojure.core/in-ns 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.comment)
(clojure.core/alias 'node 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.protocols)
(clojure.core/load "/deps/cljfmt/v0v1v10/deps/rewrite_clj/v0v4v12/rewrite_clj/node/forms")
(clojure.core/in-ns 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.forms)
(clojure.core/alias 'node 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.protocols)
(clojure.core/load "/deps/cljfmt/v0v1v10/deps/rewrite_clj/v0v4v12/rewrite_clj/node/integer")
(clojure.core/in-ns 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.integer)
(clojure.core/alias 'node 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.protocols)
(clojure.core/load "/deps/cljfmt/v0v1v10/deps/rewrite_clj/v0v4v12/rewrite_clj/node/keyword")
(clojure.core/in-ns 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.keyword)
(clojure.core/alias 'node 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.protocols)
(clojure.core/load "/deps/cljfmt/v0v1v10/deps/rewrite_clj/v0v4v12/rewrite_clj/node/quote")
(clojure.core/in-ns 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.quote)
(clojure.core/alias 'node 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.protocols)
(clojure.core/load "/deps/cljfmt/v0v1v10/deps/rewrite_clj/v0v4v12/rewrite_clj/node/string")
(clojure.core/in-ns 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.string)
(clojure.core/alias 'node 'deps.cljfmt.v0v1v10.deps.rewrite-clj.v0v4v12.rewrite-clj.node.protocols)
(clojure.core/load "/deps/toolsreader/v0v9v2/clojure/tools/reader/edn")
(clojure.core/load "/deps/toolsreader/v0v9v2/clojure/tools/reader/reader_types")
(clojure.core/load "/deps/toolsreader/v0v9v2/clojure/tools/reader/impl/utils")
(clojure.core/load "/deps/toolsreader/v0v9v2/clojure/tools/reader/impl/ExceptionInfo")

CompilerException java.lang.ExceptionInInitializerError, compiling:(afterglow/examples.clj:1:1) 
```

There's a huge amount of output. I can send you all of it if you want. Does this suggest it's something related to the toolsreader?

**Comment by brunchboy** [comment]
Wow, I don’t really understand how to interpret those lines, but it does seem to suggest the problem is something related to `tools.reader`. I received a response in the Clojure group raising suspicion about that package for independent reasons: https://groups.google.com/forum/#!topic/clojure/TWKSn3qBxs0

That did not suggest a workaround, so I’m not positive what to try. I don’t have a ton of experience with Leiningen exclusions myself, but it might be worth trying something like this in your `project.clj`:

```clojure
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/tools.reader "0.10.0"]  ; Or perhaps 1.0.0-alpha1
                 [afterglow "0.1.4" :exclusions [org.clojure/tools.reader]]]
```

I am not postive that exclusion will pass on through recursively to the packages Afterglow depends on, and prevent them from loading the possibly-problematic 0.9.2 version, but it is worth a try (and seeing what `lein deps :tree` reports once you do).

I should also try adding some exclusions myself to get rid of some conflict warnings before I cut the next release of Afterglow. I’d like to get rid of a dependency or two when I have some time: move to `core.async` everywhere rather than the somewhat redundant claypoole, for example. But Afterglow depends on a lot because it does a lot.

**Comment by brunchboy** [comment]
OK, I have updated dependencies in Afterglow, explicitly specified version 0.10.0 for `tools.reader` and cleaned up the conflicts that `lein deps :tree` reports. I have pushed a snapshot build of Afterglow 0.1.5 to Clojars, so could you try updating your `project.clj` to depend on `[afterglow "0.1.5-SNAPSHOT"]` and see if that works any better for you? As a bonus you will get all the unreleased features… and bugs, of course. :wink:

**Comment by allforabit** [comment]
I'm still getting the same errors unfortunately! I'm not sure if this is any help but here's the output when I run `(require 'afterglow.examples :verbose) ` for a second time:
```
example.core=> (require 'afterglow.examples :verbose)
(clojure.core/load "/afterglow/examples")
(clojure.core/in-ns 'afterglow.examples)
(clojure.core/alias 'beyond 'afterglow.beyond)
(clojure.core/in-ns 'afterglow.examples)
(clojure.core/alias 'push 'afterglow.controllers.ableton-push)
(clojure.core/in-ns 'afterglow.examples)
(clojure.core/alias 'ct 'afterglow.controllers)
(clojure.core/load "/afterglow/core")

CompilerException java.lang.NoClassDefFoundError: Could not initialize class afterglow.core__init, compiling:(afterglow/examples.clj:1:1) 
```

**Comment by brunchboy** [comment]
Well, rats.

I think that after a require fails, running another without `:reload-all` is pretty meaningless, because you have partially-loaded namespaces. What does a `lein deps :tree` look like in your current state? And I wonder if a `lein clean` might help somehow?

**Comment by brunchboy** [comment]
Another angle to try… maybe we can remove Leiningen and see if we get stack traces? What happens if you run `lein uberjar` and then `java -cp target/example.jar clojure.main`? That should bring up a repl that is equivalent to `lein repl` only with everything compiled into a single big jar file so it can be run withougt Leiningen. From that repl, does `(require 'afterglow.examples)` do anything different?

Failing that, what if you change your project to use `[org.clojure/clojure "1.8.0-RC1"]` rather than 1.7.0? Totally a shot in the dark, but it might help shed more light on what is failing?

**Comment by allforabit** [comment]
Hi I tried both of these suggestions but I'm still getting the same error. Maybe it'd be best to treat this issue as low priority for now. I can use the cloned repo to play around with which works fine. There's also a chance that the issue might be specific to my computer. I'll report back if I can manage to find a solution. I know it's very difficult for you to figure out when you can't repeat the issue on your computer.

**Comment by brunchboy** [comment]
I agree that it makes sense for you to go forward with the cloned version in terms of learning and exploring, but am frustrated by this mystery! Did you ever try typing `*e` right after the error first happens to see if you can get a stack trace?

**Comment by allforabit** [comment]
Here you go:

```
CompilerException java.lang.ExceptionInInitializerError, compiling:(afterglow/examples.clj:1:1) 
example.core=> *e
#error {
 :cause "Could not locate deps/toolsreader/v0v9v2/clojure/tools/reader/impl/ExceptionInfo__init.class or deps/toolsreader/v0v9v2/clojure/tools/reader/impl/ExceptionInfo.clj on classpath."
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message "java.lang.ExceptionInInitializerError, compiling:(afterglow/examples.clj:1:1)"
   :at [clojure.lang.Compiler load "Compiler.java" 7372]}
  {:type java.lang.ExceptionInInitializerError
   :message nil
   :at [java.lang.Class forName0 "Class.java" -2]}
  {:type java.io.FileNotFoundException
   :message "Could not locate deps/toolsreader/v0v9v2/clojure/tools/reader/impl/ExceptionInfo__init.class or deps/toolsreader/v0v9v2/clojure/tools/reader/impl/ExceptionInfo.clj on classpath."
   :at [clojure.lang.RT load "RT.java" 456]}]
 :trace
 [[clojure.lang.RT load "RT.java" 456]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [deps.toolsreader.v0v9v2.clojure.tools.reader.impl.utils$loading__5340__auto____23164 invoke "utils.clj" 9]
  [deps.toolsreader.v0v9v2.clojure.tools.reader.impl.utils__init load nil 9]
  [deps.toolsreader.v0v9v2.clojure.tools.reader.impl.utils__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 649]
  [clojure.core$use invokeStatic "core.clj" 5862]
  [clojure.core$use doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [deps.toolsreader.v0v9v2.clojure.tools.reader.reader_types$loading__5340__auto____23162 invoke "reader_types.clj" 9]
  [deps.toolsreader.v0v9v2.clojure.tools.reader.reader_types__init load nil 9]
  [deps.toolsreader.v0v9v2.clojure.tools.reader.reader_types__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 649]
  [clojure.core$use invokeStatic "core.clj" 5862]
  [clojure.core$use doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [deps.toolsreader.v0v9v2.clojure.tools.reader.edn$loading__5340__auto____23160 invoke "edn.clj" 9]
  [deps.toolsreader.v0v9v2.clojure.tools.reader.edn__init load nil 9]
  [deps.toolsreader.v0v9v2.clojure.tools.reader.edn__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node.string$loading__5340__auto____23158 invoke "string.clj" 1]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node.string__init load nil 1]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node.string__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5780]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node.coerce$loading__5340__auto____22820 invoke "coerce.clj" 1]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node.coerce__init load nil 1]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node.coerce__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5780]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node$loading__5340__auto____22818 invoke "node.clj" 1]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node__init load nil 1]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.node__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5780]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.parser.core$loading__5340__auto____22816 invoke "core.clj" 1]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.parser.core__init load nil 1]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.parser.core__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.parser$loading__5340__auto____22814 invoke "parser.clj" 1]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.parser__init load nil 1]
  [deps.cljfmt.v0v1v10.deps.rewrite_clj.v0v4v12.rewrite_clj.parser__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 482]
  [deps.cljfmt.v0v1v10.cljfmt.core$loading__5340__auto____22812 invoke "core.clj" 1]
  [deps.cljfmt.v0v1v10.cljfmt.core__init load nil 1]
  [deps.cljfmt.v0v1v10.cljfmt.core__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 703]
  [cider.nrepl.middleware.format$loading__5340__auto____22810 invoke "format.clj" 1]
  [cider.nrepl.middleware.format__init load nil 1]
  [cider.nrepl.middleware.format__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 2422]
  [cider.nrepl$loading__5340__auto____19807 invoke "nrepl.clj" 1]
  [cider.nrepl__init load nil 1]
  [cider.nrepl__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 2088]
  [afterglow.core$loading__5340__auto____25 invoke "core.clj" 1]
  [afterglow.core__init load nil 1]
  [afterglow.core__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2168]
  [clojure.lang.RT classForName "RT.java" 2177]
  [clojure.lang.RT loadClassForName "RT.java" 2196]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 3894]
  [afterglow.examples$eval418$loading__5565__auto____419 invoke "examples.clj" 1]
  [afterglow.examples$eval418 invokeStatic "examples.clj" 1]
  [afterglow.examples$eval418 invoke "examples.clj" -1]
  [clojure.lang.Compiler eval "Compiler.java" 6913]
  [clojure.lang.Compiler eval "Compiler.java" 6902]
  [clojure.lang.Compiler load "Compiler.java" 7360]
  [clojure.lang.RT loadResourceScript "RT.java" 372]
  [clojure.lang.RT loadResourceScript "RT.java" 363]
  [clojure.lang.RT load "RT.java" 453]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5673 invoke "core.clj" 5895]
  [clojure.core$load invokeStatic "core.clj" 5894]
  [clojure.core$load_one invokeStatic "core.clj" 5694]
  [clojure.core$load_one invoke "core.clj" -1]
  [clojure.core$load_lib$fn__5622 invoke "core.clj" 5739]
  [clojure.core$load_lib invokeStatic "core.clj" 5738]
  [clojure.core$load_lib doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$load_libs invokeStatic "core.clj" 5776]
  [clojure.core$load_libs doInvoke "core.clj" -1]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 647]
  [clojure.core$require invokeStatic "core.clj" 5798]
  [clojure.core$require doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [example.core$eval412 invokeStatic "form-init181386988127918686.clj" 1]
  [example.core$eval412 invoke "form-init181386988127918686.clj" -1]
  [clojure.lang.Compiler eval "Compiler.java" 6913]
  [clojure.lang.Compiler eval "Compiler.java" 6876]
  [clojure.core$eval invokeStatic "core.clj" 3107]
  [clojure.core$eval invoke "core.clj" -1]
  [clojure.main$repl$read_eval_print__7402$fn__7405 invoke "main.clj" 240]
  [clojure.main$repl$read_eval_print__7402 invoke "main.clj" 240]
  [clojure.main$repl$fn__7411 invoke "main.clj" 258]
  [clojure.main$repl invokeStatic "main.clj" 258]
  [clojure.main$repl doInvoke "main.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 1523]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__20325 invoke "interruptible_eval.clj" 87]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 645]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1883]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" -1]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 85]
  [clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__20370$fn__20373 invoke "interruptible_eval.clj" 222]
  [clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__20365 invoke "interruptible_eval.clj" 190]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by brunchboy** [comment]
Actually, yes, that is very helpful! It points a somewhat smoking gun at a package that @ryfow was suspicious of and we were chatting about just yesterday. I embed `cider-nrepl` in there so that even when I am running Afterglow from an überjar, I can connect to it from CIDER in Emacs and have the full power of that environment. However, that pulls in an awful lot of complexity and bloat for users who may never even try to attach a REPL to the standalone jar, never mind try to use CIDER with it. So I am going to remove that for now, and just accept that if I (or anyone) wants to work with Afterglow from CIDER, the way to do that is to launch Afterglow from within Emacs from the source of the project (whether Afterglow itself, or some other project which embeds it). I will make a new snapshot right now which removes it.

**Comment by brunchboy** [comment]
All right, that is done. And probably a good idea even if it _doesn’t_ solve your problem: The Afterglow library is now 20% smaller! A huge cost for a very small and unlikely benefit. So, if you ever have the heart to try again, I’d suggest doing a `lein clean` and then `lein -U repl` to make sure Leiningen pulls in the latest snapshot of Afterglow 0.1.5, even if it already downloaded one today.

**Comment by allforabit** [comment]
Yes it works now! Thanks very much, great detective work! It will be much easier to use it as a dependency of a project. All of the instructions on the readme work perfectly now.

**Comment by brunchboy** [comment]
That is fantastic news! Thanks @ryfow for pointing me in the right direction. :trophy:

**Comment by brunchboy** [comment]
BTW, @allforabit, if you would be willing to indulge my curiosity, I would love to know what you are thinking of building. And please don’t hesitate to ask for help with fixture definitions when it comes to working with actual lights, I know the learning curve there is pretty steep right now.

**Comment by ryfow** [comment]
:100: Glad to help!

**Comment by allforabit** [comment]
@brunchboy oddly enough I'm not using the project for dmx at the moment. I may look at this in the future. What I'm interested in is the syncing capabilities of the library. I've been looking for something like this for a while. Overtone has midi integration but doesn't have midi sync. I'm looking at using afterglow to generate synced lfos and midi data to send to ableton live. 

There's loads of other parts of afterglow that look cool as well such as the integration with ableton push and some of the concepts such as shows and the way the effects processing is setup. Loads to explore and learn! 

I'm probably not entirely using the library as intended but I suppose that's the nature of open source! 

My next step will be to look at the "beyond" code to see how you've integrated a non dmx system.

**Comment by brunchboy** [comment]
Oh, cool! Yes, there is really no “intended” use, but if you go far along this path it might be worth pulling some of those pieces into their own smaller libraries, the way I did with [ola-clojure](https://github.com/brunchboy/ola-clojure#ola-clojure) so you can use just them without the overhead of all the rest.

I’ve extended the Overtone metronome quite a bit. They weren’t interested in the direction I was taking it, so it is essentially a fork at this point, although they were happy to accept my fix for some concurrency issues I later discovered.

I have the MIDI clock sync working pretty stably and reliably now, although there is undoubtedly still room for improvement. I have yet to get back to tap-tempo and give it the same kind of polish, but I don’t expect to use it much. In my own shows I always have access to something that is a bit better than raw MIDI clock (my Traktor mapping sends that plus beat phase information so I can correct clock drift, while the Pioneer DJ Link Pro gear sends precise BPM values as well as beat timing).

My Ableton Push controller code certainly has a ton in it which could be useful outside of Afterglow. That is probably worth some effort pulling into a separate project with a more well-conceived API. But I am currently crestfallen about Ableton’s replacement of the Push hardware with the new Push 2. I need to borrow my friend’s (he’s the local Ableton rep, so has had it for weeks before the announcement) and see how radically it has changed, how much works already, and how much effort it will be to support. Sigh, so much to do, so little time!

Have fun exploring! It sounds likely that lots of ideas and code will come out of this that can make Afterglow better.

**Comment by allforabit** [comment]
Yes my thoughts exactly on abstracting to smaller libraries. A lot of the functionality looks generally useful, outside of the initial dmx use case. 

For now I'm going to start playing with the library as is and down the line see if there's anything useful that I can contribute back.

Thanks again for the fix. Have fun playing around with the new push, looks like an amazing piece of kit!

**Comment by brunchboy** [comment]
Sounds good! Did you notice Ableton’s announcement of their new Link protocol today? I’ve requested access to the SDK, but they say it could be up to two weeks before I hear a response. I hope the protocol is openly documented. It may be extremely useful to you too: https://www.ableton.com/en/blog/link-now-in-live-beta/

**Comment by allforabit** [comment]
Yes looks very interesting and could provide proper accurate syncing. I've signed up for the sdk as well. Although only seems to be ios at the moment. Looks very interesting though. Hopefully it'll be OK to use in an open source project.

**Comment by brunchboy** [comment]
I haven’t signed their SDK agreement yet, because my initial scan of it made me believe that it might prevent me from reverse-engineering the protocol to work with Afterglow. If a careful re-reading confirms that feeling, I will reply thanking them but declining for now, and say that I am looking forward for open documentation of the protocol in order to allow Live to sync nicely with open-source projects.
